name: License Scanning for Maven

defaults:
  run:
    shell: bash
    working-directory: setup

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - '**/pom.xml'
      - '.github/workflows/license-scanning-maven.yml'

env:
  ALLOW_LICENSES: "'The Apache Software License, Version 2.0' and licenses/license/name!='BSD' and licenses/license/name!='BSD-style license' and licenses/license/name!='Apache License, Version 2.0'"
  REPORT_PATH: "target/generated-resources/licenses.xml"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install XQ
      run: pip install xq
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: License XML report
      run: mvn org.codehaus.mojo:license-maven-plugin:2.0.0:download-licenses
      working-directory: setup
    - name: Validate XML report
      run: |
        LICENSE_REPORT=`xq "//dependency[licenses/license/name!=${{ env.ALLOW_LICENSES }}]" ./${{ env.REPORT_PATH }}`
        LINES_FOUND=`echo $LICENSE_REPORT | wc -l`
        echo "License issues found ..."
        if [ $LINES_FOUND -gt 1 ]; then echo $LICENSE_REPORT ; exit -1; fi
      working-directory: setup
    - name: Upload license reports
      uses: actions/upload-artifact@v4
      with:
        name: license-reports
        path: '**/dependencies.html'
    - name: Upload license XML reports
      uses: actions/upload-artifact@v4
      with:
        name: license-xml-report
        path: '**/${{ env.REPORT_PATH }}'